name: autoUpdate

env:
  VERSION: v1.0.0

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    name: autoRelease
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Start Downloading
      run: python getTerriaComic.py 2864
      
    - name: Zip files
      run: zip -r Asset.zip *
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Asset.zip
        tag_name: ${{ env.VERSION }}
        name: Release ${{ env.VERSION }}
        body: 第一个稳定版本\n新增漫画补全功能，并改用在终端中传参。\n\nPS:目前的补全是以漫画文件夹名称是否存在作为参考依据，所以没办法给只是缺页的漫画补全后续应该会添加缺页补全的功能